/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkoutsRouteImport } from './routes/_app/workouts'
import { Route as AppOrganizationsRouteImport } from './routes/_app/organizations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAthletesRouteImport } from './routes/_app/athletes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkoutsRoute = AppWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAthletesRoute = AppAthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/athletes': typeof AppAthletesRoute
  '/dashboard': typeof AppDashboardRoute
  '/organizations': typeof AppOrganizationsRoute
  '/workouts': typeof AppWorkoutsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/athletes': typeof AppAthletesRoute
  '/dashboard': typeof AppDashboardRoute
  '/organizations': typeof AppOrganizationsRoute
  '/workouts': typeof AppWorkoutsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/athletes': typeof AppAthletesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/organizations': typeof AppOrganizationsRoute
  '/_app/workouts': typeof AppWorkoutsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/athletes'
    | '/dashboard'
    | '/organizations'
    | '/workouts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/athletes'
    | '/dashboard'
    | '/organizations'
    | '/workouts'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/athletes'
    | '/_app/dashboard'
    | '/_app/organizations'
    | '/_app/workouts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workouts': {
      id: '/_app/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AppWorkoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizations': {
      id: '/_app/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/athletes': {
      id: '/_app/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AppAthletesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAthletesRoute: typeof AppAthletesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppWorkoutsRoute: typeof AppWorkoutsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAthletesRoute: AppAthletesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppWorkoutsRoute: AppWorkoutsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
